[package]
name = "haphazard"
version = "0.1.0"
edition = "2018"

[features]
std = []
multiply_hash = []
null_hash = []
ptr_hash = []

default = ["std", "ptr_hash"]

[dependencies]

[target.'cfg(loom)'.dependencies]
loom = "0.5"
